import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:provider/provider.dart';
import 'core/providers/agent_session_provider.dart';
import 'core/router.dart';
import 'core/providers/language_provider.dart';
import 'core/providers/diagnosis_provider.dart';
// Generated by: dart run flutter gen-l10n
// Do NOT edit this file manually.
import 'l10n/app_localizations.dart';

void main() {
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => DiagnosisProvider()),
        ChangeNotifierProvider(create: (_) => LanguageProvider()),
        ChangeNotifierProvider(create: (_) => AgentSessionProvider()),  // ← ADD THIS
      ],
      child: const AgriFixApp(),
    ),
  );
}
class AgriFixApp extends StatelessWidget {
  const AgriFixApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(
          create: (_) => LanguageProvider()..loadSavedLocale(),
        ),
        ChangeNotifierProvider(create: (_) => DiagnosisProvider()),
      ],
      // Consumer rebuilds MaterialApp when locale changes →
      // every Text(l10n.xxx) across the whole app switches instantly.
      child: Consumer<LanguageProvider>(
        builder: (context, langProvider, _) {
          return MaterialApp.router(
            title: 'AgriFixAR',
            debugShowCheckedModeBanner: false,

            localizationsDelegates: const [
              AppLocalizations.delegate,
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
              GlobalCupertinoLocalizations.delegate,
            ],
            supportedLocales: kSupportedLocales,
            locale: langProvider.locale,

            theme: ThemeData(
              useMaterial3: true,
              colorSchemeSeed: const Color(0xFF22C55E),
              splashFactory: NoSplash.splashFactory,
              highlightColor: Colors.transparent,
            ),

            routerConfig: appRouter,
          );
        },
      ),
    );
  }
}